package com.blog.by.kotor.exception;

public enum NotNullParam {
    CATEGORY_ID,
    CATEGORY_NAME,

    COMMENT_ID,
    COMMENT_POST_ID,
    COMMENT_USER_ID,
    COMMENT_CONTENT,
    COMMENT_CREATED_AT,

    FILTER_ID,
    FILTER_NAME,
    FILTER_CRITERIA,

    OPTION_ID,
    OPTION_QUESTION_ID,
    OPTION_TEXT,

    POLL_ID,
    POLL_USER_ID,
    POLL_DESCRIPTION,
    POLL_TITLE,
    POLL_CREATED_AT,

    POST_ID,
    POST_IS_PREMIUM,
    POST_IS_PUBLISHED,
    POST_USER_ID,
    POST_CONTENT,
    POST_TITLE,
    POST_DATE_PUBLISHED,

    POST_CATEGORY_CATEGORY_ID,
    POST_CATEGORY_POST_ID,

    POST_TAG_POST_ID,
    POST_TAG_TAG_ID,

    PREMIUM_SUBSCRIPTION_ID,
    PREMIUM_SUBSCRIPTION_USER_ID,
    PREMIUM_SUBSCRIPTION_START_DATE,
    PREMIUM_SUBSCRIPTION_END_DATE,

    QUESTION_ID,
    QUESTION_POLL_ID,
    QUESTION_TEXT,

    ROLE_ID,
    ROLE_NAME,

    TAG_ID,
    TAG_NAME,

    USER_ID,
    USER_NAME,
    USER_EMAIL,
    USER_PASSWORD,
    USER_CREATED_AT,

    USER_ROLE_ROLE_ID,
    USER_ROLE_USER_ID,

    VOTE_ID,
    VOTE_OPTION_ID,
    VOTE_POST_ID,
    VOTE_USER_ID
}
